ProvaCandidato.Web/Controllers/ClienteObservacaoController.cs
using ProvaCandidato.Code;
using ProvaCandidato.Data.Entidade;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProvaCandidato.Controllers
{
    public class ClienteObservacaoController : SuperController
    {
        #region VIEWS
        public ActionResult _PartialCadastro(int ClienteId)
        {
            Cliente cliente = ClienteBLL.Consultar(ClienteId);
            if (cliente == null)
            {
                MensagemErro("Cliente não encontrado");
                return RedirectToAction("Cadastro", "Cliente", ClienteId);
            }
            ViewBag.Cliente = $"{cliente.Codigo} - {cliente.Nome}";
            return PartialView("_PartialCadastro", new ClienteObservacao(ClienteId));
        }

        #endregion VIEWS

        #region SERVIÇOS

        [HttpGet]
        public ActionResult Consultar(int ClienteId)
        {
            string msgFalha = $"Falha ao consultar observações do cliente.";
            try
            {
                string validacao = "";
                var resultados = ClienteObservacaoBLL.Consultar(ClienteId, out validacao);
                return RetornoJson(resultados, msgFalha, validacao: validacao);
            }
            catch (Exception ex)
            {
                return JsonErro(msgFalha, ex.Message);
            }
        }

        [HttpPost]
        public ActionResult Inserir(ClienteObservacao observacao)
        {
            string msgSucesso = $"Observação cadastrada com sucesso.";
            string msgFalha = $"Falha ao cadastrar observação.";
            try
            {
                if (!ModelState.IsValid)
                    return JsonErro(msgFalha, "Modelo inválido!");

                string validacao = "";
                bool sucesso = ClienteObservacaoBLL.Inserir(observacao, out validacao);
                return RetornoJson(sucesso, msgFalha, msgSucesso, validacao);
            }
            catch (Exception ex)
            {
                return JsonErro(msgFalha, ex.Message);
            }
        }

        #endregion SERVIÇOS
    }
}

ProvaCandidato.Web/Views/ClienteObservacao/_PartialCadastro.cshtml
@using ProvaCandidato.Data.Entidade;
@model ClienteObservacao
@{
    string idModal = Model.GetType().Name;
}

<form id="formulario@(idModal)">
    <div>
        <h4 id="titulo@(idModal)">Cliente: @ViewBag.Cliente</h4>
        <hr />
    </div>
    @Html.Partial("~/Views/Shared/Alerta/Alerta.cshtml")
    <div id="divCadastro@(idModal)">
        @Html.HiddenFor(f => f.ClienteId)
        @Html.LabelFor(f => f.Observacao)
        @Html.TextAreaFor(f => f.Observacao, new { @class = "w-100" })
    </div>
</form>

<script>
    $(document).ready(() => {
        jsLoading(false);
    });
    function AdicionaObservacao() {
        var data = { observacao: $('#formulario@(idModal)').serializeArray().serializeObject() };
        console.log(data);
        var url = `@Url.Action("Inserir", "ClienteObservacao")`;
        Post(url, data, FechaModalObservacao);
    }

    function FechaModalObservacao() {
        $(`:input`, `#formulario@(idModal)`)
            .not(":button, :submit, :reset").val("");

        $(`#formulario@(idModal)`).closest(`.ui-dialog-content`).dialog("close");
    }
</script>